import fs from "node:fs";
import path from "node:path";
import { loadAllTechniques, loadRoadmap } from "../lib/content";
import { VIDEO_TYPES, type Technique } from "../lib/schema";
import {
  GENERATED_DIR,
  log,
  parseIsoDuration,
  ROOT,
  style,
} from "./_shared";

/**
 * `npm run curation:sheet`
 *
 * Writes docs/CURATION.md — the worksheet for picking clips.
 *
 * Generated rather than hand-written, because the interesting part is what is
 * *still missing*, and that changes every time a technique is drafted or a
 * clip lands. A static checklist would be wrong within a day.
 *
 * Anything typed between the `<!-- picks:slug -->` markers is carried across
 * regenerations untouched. That matters: this file is filled in over days, and
 * a generator that silently ate somebody's afternoon of work would be worse
 * than no generator at all.
 */

const OUT = path.join(ROOT, "docs", "CURATION.md");

const PICK_START = (slug: string) => `<!-- picks:${slug} -->`;
const PICK_END = (slug: string) => `<!-- /picks:${slug} -->`;

const PLACEHOLDER = [
  "<!-- One line per clip:",
  "     URL | type | optional note",
  `     type is one of: ${VIDEO_TYPES.join(", ")}`,
  "     Put the timestamp in the URL. On YouTube: Share → tick “Start at”.",
  "     Add | end=128 if you also want the clip to stop. -->",
  "",
].join("\n");

/** Pull each technique's existing picks out of the file we are about to replace. */
function existingPicks(): Map<string, string> {
  const picks = new Map<string, string>();
  if (!fs.existsSync(OUT)) return picks;

  const current = fs.readFileSync(OUT, "utf8");
  const pattern = /<!-- picks:([a-z0-9-]+) -->\n([\s\S]*?)<!-- \/picks:\1 -->/g;

  for (const match of current.matchAll(pattern)) {
    const [, slug, body] = match;
    // A block holding nothing but the placeholder comment has not been filled
    // in. Carrying those forward would both miscount the progress line and
    // freeze the instructions at whatever they said the first time.
    const withoutComments = body.replace(/<!--[\s\S]*?-->/g, "").trim();
    if (withoutComments.length > 0) picks.set(slug, body);
  }
  return picks;
}

type AutoVideo = {
  youtubeId: string;
  title: string;
  channel: string;
  publishedAt: string;
  duration: string;
};

function loadCandidates(): Record<string, { query: string; results: AutoVideo[] }> {
  const file = path.join(GENERATED_DIR, "videos-auto.json");
  if (!fs.existsSync(file)) return {};
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return {};
  }
}

/** What still stands between this technique and `published`. */
function gap(t: Technique): string[] {
  const missing: string[] = [];
  const instruction = t.videos.filter((v) => v.type === "instruction").length;

  if (t.videos.length < 2) {
    missing.push(`${2 - t.videos.length} more clip(s) — two is the minimum`);
  }
  if (instruction === 0) {
    missing.push("at least one clip of type `instruction`");
  }
  if (t.summary.startsWith("TODO") || t.howTo.some((s) => s.startsWith("TODO"))) {
    missing.push("the text is still a skeleton");
  }
  return missing;
}

function mmss(iso: string): string {
  const total = parseIsoDuration(iso);
  return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`;
}

// ---------------------------------------------------------------------------

const carried = existingPicks();
const techniques = [...loadAllTechniques().values()];
const roadmap = loadRoadmap();
const candidates = loadCandidates();

const order = new Map(roadmap.techniques.map((t, i) => [t.slug, i]));
techniques.sort(
  (a, b) => (order.get(a.slug) ?? 999) - (order.get(b.slug) ?? 999),
);

const p0 = roadmap.techniques.filter((t) => t.priority === "P0");
const byslug = new Map(techniques.map((t) => [t.slug, t]));
const p0Published = p0.filter(
  (t) => byslug.get(t.slug)?.status === "published",
);
const needClips = techniques.filter((t) => gap(t).length > 0);
const notDrafted = roadmap.techniques.filter((t) => !byslug.has(t.slug));

const lines: string[] = [];

lines.push(
  "<!-- Generated by `npm run curation:sheet`. Your picks are preserved on regeneration;",
  "     everything outside the picks blocks is rewritten, so do not edit it by hand. -->",
  "",
  "# Clip curation worksheet",
  "",
  "Fill this in whenever you have time. Tell me when there is anything in it and",
  "I will run `add:video`, verify each clip plays from the timestamp, and flip the",
  "technique to `published`.",
  "",
  "## How to fill it in",
  "",
  "Under each technique, between the `picks` comment markers, put **one line per clip**:",
  "",
  "```",
  "https://youtu.be/ivv-cQ03v8s?t=20 | instruction | watch the knee bend",
  "```",
  "",
  "- **The timestamp lives in the URL.** On YouTube, hit Share and tick “Start at” —",
  "  it builds the URL for you at the second you paused on.",
  `- **Type** is one of: ${VIDEO_TYPES.map((t) => `\`${t}\``).join(", ")}.`,
  "  `gameplay` means the shot in a real rally rather than a lesson.",
  "- **Note** is optional and shows under the clip on the page.",
  "- Add `| end=128` if the clip should stop as well as start.",
  "",
  "## The gate",
  "",
  "A technique cannot be published until it has **two clips, at least one of them",
  "`instruction`**. That is enforced by the schema, not by me — a build fails otherwise.",
  "",
  "Two is a floor, not a target. Three or four is better if the shot has a good",
  "slow-motion clip or a clear example from a real game.",
  "",
  "## Where it stands",
  "",
  `- **P0 progress:** ${p0Published.length} of ${p0.length} published`,
  `- **Waiting on you:** ${needClips.length} technique(s) below`,
  `- **Not drafted yet:** ${notDrafted.length} (they appear here once I write them)`,
  "",
  "---",
  "",
);

for (const t of techniques) {
  const missing = gap(t);
  const status = missing.length === 0 ? "✅ ready" : "⏳ needs clips";

  lines.push(
    `## ${t.name}`,
    "",
    `\`${t.slug}\` · ${t.category} · ${t.difficulty} · **${status}**`,
    "",
  );

  if (t.videos.length > 0) {
    lines.push("Already curated:", "");
    for (const v of t.videos) {
      const at = v.start > 0 ? ` from ${Math.floor(v.start / 60)}:${String(v.start % 60).padStart(2, "0")}` : "";
      lines.push(`- ${v.title} — ${v.channel} · ${v.type}${at}`);
    }
    lines.push("");
  }

  if (missing.length > 0) {
    lines.push(`**Still needed:** ${missing.join("; ")}.`, "");
  } else {
    lines.push(
      "Nothing needed. Add more only if you find something clearly better.",
      "",
    );
  }

  lines.push(PICK_START(t.slug));
  lines.push(carried.get(t.slug)?.replace(/\s+$/, "") ?? PLACEHOLDER.trimEnd());
  lines.push(PICK_END(t.slug), "");

  const found = candidates[t.slug];
  if (found && found.results.length > 0) {
    lines.push(
      "<details>",
      `<summary>${found.results.length} candidates from <code>${found.query}</code> — titles only, nobody has watched these</summary>`,
      "",
      "| | Length | Title | Channel | Link |",
      "|---|---|---|---|---|",
    );
    found.results.forEach((r, i) => {
      const title = r.title.replace(/\|/g, "\\|");
      lines.push(
        `| ${i + 1} | ${mmss(r.duration)} | ${title} | ${r.channel} | https://youtu.be/${r.youtubeId} |`,
      );
    });
    lines.push("", "</details>", "");
  } else {
    lines.push(
      "_No candidates fetched yet — run `npm run fetch:videos -- --only " +
        t.slug +
        "`._",
      "",
    );
  }

  lines.push("---", "");
}

if (notDrafted.length > 0) {
  lines.push(
    "## Not drafted yet",
    "",
    "These have no text yet, so there is nothing to attach clips to. They get a",
    "section above as each batch is written.",
    "",
  );
  for (const t of notDrafted) {
    lines.push(`- ${t.name} \`${t.slug}\` · ${t.priority}`);
  }
  lines.push("");
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join("\n"), "utf8");

log.ok(`wrote ${style.cyan(path.relative(ROOT, OUT))}`);
if (carried.size > 0) {
  log.info(
    style.dim(`  carried over picks for ${carried.size} technique(s)`),
  );
}
log.info(
  style.dim(
    `  ${needClips.length} technique(s) waiting on clips · P0 ${p0Published.length}/${p0.length}`,
  ),
);
